# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlPoint-Converters
version:      1.0205
version_from: lib/PerlPoint/Converters.pm
installdirs:  site
requires:
    Getopt::ArgvFile:              1.01
    PerlPoint::Parser:             0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
